name: CI/CD via Tailscale

on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout your code
      - uses: actions/checkout@v3

      # 2. Install Tailscale on the runner and join your Tailnet
      - name: Install & start Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:smzi-ci
          # optional: tailnet key expiry, e.g. --authkey-expiry=1h

      # 3. Wait for Tailscale to be up, then verify
      - name: Show Tailscale status
        run: |
          tailscale status
          echo "Runner is now in your Tailnet, IPs:"
          tailscale ip -4

      # 4. Build your Next.js app
      - name: Set up Node.js & build
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - run: |
          npm ci
          npm run build

      - name: Write KEY to temp file & show size
        run: |
          echo "Saving KEY to file…"
          printf '%s' "$KEY" > ./keyfile
          echo "keyfile size (bytes):"
          wc -c ./keyfile
        env:
          KEY: ${{ secrets.KEY }}

      # 5. Deploy via SSH over Tailscale
      - name: Deploy to server over Tailscale
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }} # Tailscale IP
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          #key: ${{ secrets.KEY }} # your SSH private key
          port: ${{ secrets.PORT }}
          script: |
            cd /home/deploy/sites/sebastien-morazzani
            git pull origin main
            npm install
            npm run build
            pm2 restart sebastien-morazzani || pm2 start npm --name "sebastien-morazzani" -- run start
