name: CI/CD Pipeline
run-name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.18.0'
      
      - name: Install dependencies
        run: npm ci

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Starting deployment..."
            cd /home/deploy/sites/sebastien-morazzani
            echo "Pulling latest changes from main branch..."
            git pull origin main
            echo "Installing dependencies and building the project..."
            npm install
            echo "Building the project..."
            npm run build
            echo "Build successful"
            pm2 restart "sebastien-morazzani" || pm2 start npm --name "sebastien-morazzani" -- run start
            echo "Deployment completed successfully"

     
          


